export function Emoji() {
    return (
       
        <div className="bg-white text-slate-800 h-screen">
         <p className="bg-slate-900 text-slate-100 rounded p-1 w-64 text-xl flex justify-center m-2">Smileys</p>
         {/* Emojis */}
         <div className="columns-9 w-64  text-xl
         rounded  p-1">
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😀</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😃</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😄</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😁</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😆</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😅</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😂</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤣</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😊</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😇</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🙂</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🙃</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😉</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😌</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😍</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥰</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😘</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😗</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😙</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😚</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😋</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😛</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😝</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😜</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤪</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤨</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🧐</span> 
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤓</span>  
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😎</span> 
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤩</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥳</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😏</span>  
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😒</span>   
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😞</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😔</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😟</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😕</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🙁</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">☹️</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😣</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😖</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😫</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😩</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥺</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😢</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😭</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😤</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😠</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😡</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤬</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤯</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😳</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥵</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥶</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😱</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😨</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😰</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😥</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😓</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤗</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤔</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤭</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤫</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤥</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😶</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😐</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😑</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😬</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🙄</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😯</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😦</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😧</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😮</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😲</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥱</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😴</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤤</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😪</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😵</span>
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤐</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🥴</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤢</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤮</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤧</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😷</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤒</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤕</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤑</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤠</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😈</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">👿</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">👹</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">👺</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤡</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">💩</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">👻</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">💀</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">☠️</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">👽</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">👾</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🤖</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🎃</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😺</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😸</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😹</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😻</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😼</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😽</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">🙀</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😿</span>               
            <span className=" bg-slate-900 text-center rounded  hover:bg-slate-600 cursor-pointer">😾</span>                      
         </div>
        {/* fim emoji */}
        </div>
    )
}